// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubsAPI.Data;

namespace SubsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521114944_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubsAPI.Entities.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = "fdf8fe94d",
                            DateCreated = new DateTime(2023, 5, 21, 11, 49, 44, 478, DateTimeKind.Utc).AddTicks(9593),
                            Password = "DAAAAO/ETBY5JLXHIkNeuRAAAACQc/FfqR79d1QA8ucx/SBW4VCAsUAsiiSn4Q=="
                        },
                        new
                        {
                            Id = "1e471916b",
                            DateCreated = new DateTime(2023, 5, 21, 11, 49, 44, 479, DateTimeKind.Utc).AddTicks(155),
                            Password = "DAAAAGozHmFsp6U3h7X9aBAAAADqAJCyM0rzChYg/9MuBtBNNXmMJJtywpiYmw=="
                        });
                });

            modelBuilder.Entity("SubsAPI.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscribeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UnsubscribeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("SubsAPI.Models.TokenExpiration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TokenExpiration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hours = 8
                        });
                });

            modelBuilder.Entity("SubsAPI.Models.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("SubsAPI.Models.Subscriber", b =>
                {
                    b.HasOne("SubsAPI.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SubsAPI.Models.UserToken", b =>
                {
                    b.HasOne("SubsAPI.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
